name: jwizard

services:
  jwizard-rabbitmq:
    container_name: jwizard-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '${JW_RABBITMQ_AMQP_PORT:-5672}:5672'
      - '${JW_RABBITMQ_PANEL_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "jwizard-main"
    volumes:
      - ./.volumes/rabbitmq/rabbitmq-volume:/var/lib/rabbitmq
    networks:
      - jwizard-network

  jwizard-redis:
    container_name: jwizard-redis
    image: redis:7.2-alpine
    ports:
      - "${JW_REDIS_SINGLE_NODE_PORT:-6379}:6379"
    volumes:
      - ./.volumes/redis/redis-volume:/data
    networks:
      - jwizard-network

  jwizard-redis-ui:
    container_name: jwizard-redis-ui
    image: rediscommander/redis-commander:latest
    ports:
      - "${JW_REDIS_PANEL_PORT:-8081}:8081"
    environment:
      REDIS_HOSTS: local:jwizard-redis:6379
    depends_on:
      - jwizard-redis
    networks:
      - jwizard-network

  jwizard-postgres:
    container_name: jwizard-postgres
    image: postgres:16-alpine
    ports:
      - "${JW_POSTGRES_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    volumes:
      - ./.volumes/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.volumes/postgres/postgres-volume:/var/lib/postgresql/data
    networks:
      - jwizard-network

  jwizard-postgres-ui:
    container_name: jwizard-postgres-ui
    build:
      context: ./.volumes/pgadmin
    pull_policy: build
    ports:
      - "${JW_POSTGRES_PANEL_PORT:-8082}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@jwizard.xyz"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    entrypoint: /usr/local/bin/entrypoint-wrapper
    volumes:
      - ./.volumes/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./.volumes/pgadmin/pgpassfile:/tmp/mountpoint.pgpass
    depends_on:
      - jwizard-postgres
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge
