name: jwizard

services:
  jwizard-rabbitmq:
    container_name: jwizard-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '${JW_RABBITMQ_AMQP_PORT:-5672}:5672'
      - '${JW_RABBITMQ_PANEL_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "jwizard-main"
    volumes:
      - ./.volumes/rabbitmq/rabbitmq-volume:/var/lib/rabbitmq
    networks:
      - jwizard-network

  jwizard-redis:
    container_name: jwizard-redis
    image: redis:7.2-alpine
    ports:
      - "${JW_REDIS_SINGLE_NODE_PORT:-6379}:6379"
    volumes:
      - ./.volumes/redis/redis-volume:/data
    networks:
      - jwizard-network

  jwizard-redis-ui:
    container_name: jwizard-redis-ui
    image: rediscommander/redis-commander:latest
    ports:
      - "${JW_REDIS_PANEL_PORT:-8081}:8081"
    environment:
      REDIS_HOSTS: local:jwizard-redis:6379
    depends_on:
      - jwizard-redis
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge
